### ISSUE TITLE
Cannot start despite file being present

### ISSUE THREAD

**Issue by levtey** [richardhyy/EusMinerHat#2]
Getting this error whenever I start the miner despite having the file:

![image](https://user-images.githubusercontent.com/60494179/120228042-34b48880-c1ff-11eb-9d81-fbbc6f88ce2c.png)

```[13:59:27 WARN]: java.io.IOException: Cannot run program "plugins/EusMinerHat/miner/xmrig/xmrig" (in directory "plugins/EusMinerHat/miner/xmrig"): error=2, No such file or directory
[13:59:27 WARN]:        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
[13:59:27 WARN]:        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[13:59:27 WARN]:        at cc.eumc.eusminerhat.miner.MinerManager.startMining(MinerManager.java:141)
[13:59:27 WARN]:        at cc.eumc.eusminerhat.miner.MinerManager.checkAndToggleMining(MinerManager.java:115)
[13:59:27 WARN]:        at cc.eumc.eusminerhat.CheckIntervalTimer.run(CheckIntervalTimer.java:20)
[13:59:27 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:59:27 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469)
[13:59:27 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1517)
[13:59:27 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:461)
[13:59:27 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1426)
[13:59:27 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1147)
[13:59:27 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[13:59:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:59:27 WARN]: Caused by: java.io.IOException: error=2, No such file or directory
[13:59:27 WARN]:        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[13:59:27 WARN]:        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
[13:59:27 WARN]:        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[13:59:27 WARN]:        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
[13:59:27 WARN]:        ... 12 more
[13:59:27 ERROR]: [EusMinerHat] Failed starting miner: Cannot run program "plugins/EusMinerHat/miner/xmrig/xmrig" (in directory "plugins/EusMinerHat/miner/xmrig"): error=2, No such file or directory
[13:59:27 INFO]: [EusMinerHat] Miner status changed: stopped

**Comment by richardhyy** [comment]
I looked into it, and It is a bug of MinerHat.
Thank you for reporting this issue. :)

**Comment by richardhyy** [comment]
So please add `./` (i.e. change `xmrig` to `./xmrig`) before the start command, and a fix will be made in a later version.
